"""banking schema constraints and indexes"""

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "0dc7c8edf7f5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("table_name", sa.String(length=64), nullable=False),
        sa.Column("record_id", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=10), nullable=False),
        sa.Column(
            "old_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "new_values",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_by", sa.String(length=120), nullable=False),
        sa.CheckConstraint(
            "operation IN ('INSERT','UPDATE','DELETE')", name="ck_audit_operation"
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_table(
        "customers",
        sa.Column("customer_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="ACTIVE", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('ACTIVE','BLOCKED','UNDER_REVIEW')", name="ck_customer_status"
        ),
        sa.PrimaryKeyConstraint("customer_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "risk_settings",
        sa.Column("settings_id", sa.Integer(), nullable=False),
        sa.Column("fraud_threshold", sa.Double(), nullable=False),
        sa.CheckConstraint(
            "fraud_threshold > 0 AND fraud_threshold < 1", name="ck_fraud_threshold"
        ),
        sa.CheckConstraint("settings_id = 1", name="ck_single_settings"),
        sa.PrimaryKeyConstraint("settings_id"),
    )
    op.create_table(
        "accounts",
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.String(length=64), nullable=False),
        sa.Column("account_type", sa.String(length=20), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "account_type IN ('SAVINGS','CURRENT')", name="ck_account_type"
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','BLOCKED','CLOSED')", name="ck_account_status"
        ),
        sa.CheckConstraint("balance >= 0", name="ck_account_balance"),
        sa.CheckConstraint("length(currency) = 3", name="ck_currency"),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("account_id"),
        sa.UniqueConstraint("account_id", "customer_id", name="uq_account_owner"),
    )
    op.create_index(
        op.f("ix_accounts_customer_id"), "accounts", ["customer_id"], unique=False
    )
    op.create_table(
        "devices",
        sa.Column("device_id", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.String(length=64), nullable=False),
        sa.Column("device_type", sa.String(length=30), nullable=False),
        sa.Column("device_identifier", sa.String(length=120), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("trusted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("device_id"),
        sa.UniqueConstraint("device_id", "customer_id", name="uq_device_owner"),
        sa.UniqueConstraint("device_identifier"),
    )
    op.create_index(
        op.f("ix_devices_customer_id"), "devices", ["customer_id"], unique=False
    )
    op.create_table(
        "transactions",
        sa.Column("transaction_id", sa.String(length=64), nullable=False),
        sa.Column("account_id", sa.String(length=64), nullable=False),
        sa.Column("customer_id", sa.String(length=64), nullable=False),
        sa.Column("destination_account_id", sa.String(length=64), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("payment_method", sa.String(length=20), nullable=False),
        sa.Column("transaction_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("location", sa.String(length=120), nullable=True),
        sa.Column("latitude", sa.Double(), nullable=True),
        sa.Column("longitude", sa.Double(), nullable=True),
        sa.Column("device_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("balance_before", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("balance_after", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "destination_balance_before",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
        ),
        sa.Column(
            "destination_balance_after",
            sa.Numeric(precision=18, scale=2),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('PENDING','COMPLETED','FAILED','FLAGGED')",
            name="ck_transaction_status",
        ),
        sa.CheckConstraint("transaction_type = 'TRANSFER'", name="ck_transaction_type"),
        sa.CheckConstraint(
            "account_id <> destination_account_id", name="ck_different_accounts"
        ),
        sa.CheckConstraint("amount > 0", name="ck_transaction_amount"),
        sa.CheckConstraint(
            "balance_after = balance_before - amount AND destination_balance_after = destination_balance_before + amount",
            name="ck_transfer_snapshots",
        ),
        sa.CheckConstraint(
            "balance_before >= 0 AND balance_after >= 0 AND destination_balance_before >= 0 AND destination_balance_after >= 0",
            name="ck_transaction_balances",
        ),
        sa.CheckConstraint(
            "latitude IS NULL OR latitude BETWEEN -90 AND 90", name="ck_latitude"
        ),
        sa.CheckConstraint(
            "longitude IS NULL OR longitude BETWEEN -180 AND 180", name="ck_longitude"
        ),
        sa.ForeignKeyConstraint(
            ["account_id", "customer_id"],
            ["accounts.account_id", "accounts.customer_id"],
            name="fk_transaction_owner",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["destination_account_id"],
            ["accounts.account_id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id", "customer_id"],
            ["devices.device_id", "devices.customer_id"],
            name="fk_transaction_device_owner",
        ),
        sa.PrimaryKeyConstraint("transaction_id"),
    )
    op.create_index(
        "idx_transactions_account_timestamp",
        "transactions",
        ["account_id", "transaction_timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_transactions_customer_timestamp",
        "transactions",
        ["customer_id", "transaction_timestamp"],
        unique=False,
    )
    op.create_table(
        "fraud_predictions",
        sa.Column("prediction_id", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.String(length=64), nullable=False),
        sa.Column("model_name", sa.String(length=120), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("fraud_probability", sa.Double(), nullable=False),
        sa.Column("behaviour_score", sa.Double(), nullable=False),
        sa.Column("risk_score", sa.Double(), nullable=False),
        sa.Column("classification", sa.String(length=20), nullable=False),
        sa.Column(
            "features",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "classification IN ('NORMAL','SUSPICIOUS','FRAUD')",
            name="ck_classification",
        ),
        sa.CheckConstraint(
            "fraud_probability BETWEEN 0 AND 1 AND behaviour_score BETWEEN 0 AND 1 AND risk_score BETWEEN 0 AND 1",
            name="ck_prediction_scores",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.transaction_id"],
        ),
        sa.PrimaryKeyConstraint("prediction_id"),
        sa.UniqueConstraint(
            "prediction_id", "transaction_id", name="uq_prediction_transaction"
        ),
        sa.UniqueConstraint("transaction_id"),
    )
    op.create_index(
        "idx_fraud_predictions_risk", "fraud_predictions", ["risk_score"], unique=False
    )
    op.create_table(
        "fraud_alerts",
        sa.Column("alert_id", sa.String(length=64), nullable=False),
        sa.Column("transaction_id", sa.String(length=64), nullable=False),
        sa.Column("prediction_id", sa.String(length=64), nullable=False),
        sa.Column("risk_score", sa.Double(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "alert_status", sa.String(length=20), server_default="OPEN", nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_by", sa.String(length=120), nullable=True),
        sa.CheckConstraint(
            "alert_status IN ('OPEN','INVESTIGATING','RESOLVED','FALSE_POSITIVE')",
            name="ck_alert_status",
        ),
        sa.CheckConstraint("risk_score BETWEEN 0 AND 1", name="ck_alert_risk"),
        sa.ForeignKeyConstraint(
            ["prediction_id", "transaction_id"],
            ["fraud_predictions.prediction_id", "fraud_predictions.transaction_id"],
            name="fk_alert_prediction_transaction",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.transaction_id"],
        ),
        sa.PrimaryKeyConstraint("alert_id"),
        sa.UniqueConstraint("prediction_id"),
    )
    op.create_index("idx_alert_status", "fraud_alerts", ["alert_status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_alert_status", table_name="fraud_alerts")
    op.drop_table("fraud_alerts")
    op.drop_index("idx_fraud_predictions_risk", table_name="fraud_predictions")
    op.drop_table("fraud_predictions")
    op.drop_index("idx_transactions_customer_timestamp", table_name="transactions")
    op.drop_index("idx_transactions_account_timestamp", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_devices_customer_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_accounts_customer_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("risk_settings")
    op.drop_table("customers")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
